/**
 * Do not edit directly
 * Generated on Sun, 11 Sep 2022 02:36:48 GMT
 */

module.exports = {
  featuredContext: {
    'featuredContext-primary': {
      value: '#3f9ff5',
      type: 'color',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: '#3f9ff5',
        type: 'color',
      },
      name: 'featuredContext-primary',
      attributes: {},
      path: ['featuredContext', 'featuredContext-primary'],
    },
    'featuredContext-secondary': {
      value: '#CdaF75',
      type: 'color',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: '#CdaF75',
        type: 'color',
      },
      name: 'featuredContext-secondary',
      attributes: {},
      path: ['featuredContext', 'featuredContext-secondary'],
    },
  },
  icon: {
    'icon-primary': {
      value: '#000000',
      type: 'color',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: '#000000',
        type: 'color',
      },
      name: 'icon-primary',
      attributes: {},
      path: ['icon', 'icon-primary'],
    },
    'icon-secondary': {
      value: '#ffffff',
      type: 'color',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: '#ffffff',
        type: 'color',
      },
      name: 'icon-secondary',
      attributes: {},
      path: ['icon', 'icon-secondary'],
    },
  },
  button: {
    'button-primary': {
      value: '#000000',
      type: 'color',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: '#000000',
        type: 'color',
      },
      name: 'button-primary',
      attributes: {},
      path: ['button', 'button-primary'],
    },
    'button-secondary': {
      value: '#ffffff',
      type: 'color',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: '#ffffff',
        type: 'color',
      },
      name: 'button-secondary',
      attributes: {},
      path: ['button', 'button-secondary'],
    },
    'button-disabled': {
      value: '#9b9b9b',
      type: 'color',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: '#9b9b9b',
        type: 'color',
      },
      name: 'button-disabled',
      attributes: {},
      path: ['button', 'button-disabled'],
    },
  },
  surface: {
    'surface-primary': {
      value: '#e6e6e6',
      type: 'color',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: '#e6e6e6',
        type: 'color',
      },
      name: 'surface-primary',
      attributes: {},
      path: ['surface', 'surface-primary'],
    },
    'surface-secondary': {
      value: '#1d1d1f',
      type: 'color',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: '#1d1d1f',
        type: 'color',
      },
      name: 'surface-secondary',
      attributes: {},
      path: ['surface', 'surface-secondary'],
    },
  },
  text: {
    'text-primary': {
      value: '#000000',
      type: 'color',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: '#000000',
        type: 'color',
      },
      name: 'text-primary',
      attributes: {},
      path: ['text', 'text-primary'],
    },
    'text-secondary': {
      value: '#ffffff',
      type: 'color',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: '#ffffff',
        type: 'color',
      },
      name: 'text-secondary',
      attributes: {},
      path: ['text', 'text-secondary'],
    },
    'text-tertiary': {
      value: '#68686a',
      type: 'color',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: '#68686a',
        type: 'color',
      },
      name: 'text-tertiary',
      attributes: {},
      path: ['text', 'text-tertiary'],
    },
  },
  border: {
    'border-primary': {
      value: '#1d1d1f',
      type: 'color',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: '#1d1d1f',
        type: 'color',
      },
      name: 'border-primary',
      attributes: {},
      path: ['border', 'border-primary'],
    },
  },
  spectrum: {
    gray: {
      '100': {
        value: '#f3f3f3',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#f3f3f3',
          type: 'color',
        },
        name: '100',
        attributes: {},
        path: ['spectrum', 'gray', '100'],
      },
      '200': {
        value: '#e6e6e6',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#e6e6e6',
          type: 'color',
        },
        name: '200',
        attributes: {},
        path: ['spectrum', 'gray', '200'],
      },
      '300': {
        value: '#b4b4b4',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#b4b4b4',
          type: 'color',
        },
        name: '300',
        attributes: {},
        path: ['spectrum', 'gray', '300'],
      },
      '400': {
        value: '#9b9b9b',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#9b9b9b',
          type: 'color',
        },
        name: '400',
        attributes: {},
        path: ['spectrum', 'gray', '400'],
      },
      '500': {
        value: '#818183',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#818183',
          type: 'color',
        },
        name: '500',
        attributes: {},
        path: ['spectrum', 'gray', '500'],
      },
      '600': {
        value: '#68686a',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#68686a',
          type: 'color',
        },
        name: '600',
        attributes: {},
        path: ['spectrum', 'gray', '600'],
      },
      '700': {
        value: '#4f4f51',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#4f4f51',
          type: 'color',
        },
        name: '700',
        attributes: {},
        path: ['spectrum', 'gray', '700'],
      },
      '800': {
        value: '#363638',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#363638',
          type: 'color',
        },
        name: '800',
        attributes: {},
        path: ['spectrum', 'gray', '800'],
      },
      '900': {
        value: '#1d1d1f',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#1d1d1f',
          type: 'color',
        },
        name: '900',
        attributes: {},
        path: ['spectrum', 'gray', '900'],
      },
      '1000': {
        value: '#000000',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#000000',
          type: 'color',
        },
        name: '1000',
        attributes: {},
        path: ['spectrum', 'gray', '1000'],
      },
      '000': {
        value: '#ffffff',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#ffffff',
          type: 'color',
        },
        name: '000',
        attributes: {},
        path: ['spectrum', 'gray', '000'],
      },
    },
    red: {
      '100': {
        value: '#ffe5e7',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#ffe5e7',
          type: 'color',
        },
        name: '100',
        attributes: {},
        path: ['spectrum', 'red', '100'],
      },
      '200': {
        value: '#ffc2c6',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#ffc2c6',
          type: 'color',
        },
        name: '200',
        attributes: {},
        path: ['spectrum', 'red', '200'],
      },
      '300': {
        value: '#ff9ea5',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#ff9ea5',
          type: 'color',
        },
        name: '300',
        attributes: {},
        path: ['spectrum', 'red', '300'],
      },
      '400': {
        value: '#f96c73',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#f96c73',
          type: 'color',
        },
        name: '400',
        attributes: {},
        path: ['spectrum', 'red', '400'],
      },
      '500': {
        value: '#f1465a',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#f1465a',
          type: 'color',
        },
        name: '500',
        attributes: {},
        path: ['spectrum', 'red', '500'],
      },
      '600': {
        value: '#e32144',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#e32144',
          type: 'color',
        },
        name: '600',
        attributes: {},
        path: ['spectrum', 'red', '600'],
      },
      '700': {
        value: '#be1332',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#be1332',
          type: 'color',
        },
        name: '700',
        attributes: {},
        path: ['spectrum', 'red', '700'],
      },
      '800': {
        value: '#990620',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#990620',
          type: 'color',
        },
        name: '800',
        attributes: {},
        path: ['spectrum', 'red', '800'],
      },
      '900': {
        value: '#650113',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#650113',
          type: 'color',
        },
        name: '900',
        attributes: {},
        path: ['spectrum', 'red', '900'],
      },
      '1000': {
        value: '#320109',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#320109',
          type: 'color',
        },
        name: '1000',
        attributes: {},
        path: ['spectrum', 'red', '1000'],
      },
      '000': {
        value: '#fff5f5',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#fff5f5',
          type: 'color',
        },
        name: '000',
        attributes: {},
        path: ['spectrum', 'red', '000'],
      },
    },
    blue: {
      '100': {
        value: '#c1ebf6',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#c1ebf6',
          type: 'color',
        },
        name: '100',
        attributes: {},
        path: ['spectrum', 'blue', '100'],
      },
      '200': {
        value: '#96ddef',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#96ddef',
          type: 'color',
        },
        name: '200',
        attributes: {},
        path: ['spectrum', 'blue', '200'],
      },
      '300': {
        value: '#6ad0e9',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#6ad0e9',
          type: 'color',
        },
        name: '300',
        attributes: {},
        path: ['spectrum', 'blue', '300'],
      },
      '400': {
        value: '#3fc2e2',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#3fc2e2',
          type: 'color',
        },
        name: '400',
        attributes: {},
        path: ['spectrum', 'blue', '400'],
      },
      '500': {
        value: '#14b4dc',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#14b4dc',
          type: 'color',
        },
        name: '500',
        attributes: {},
        path: ['spectrum', 'blue', '500'],
      },
      '600': {
        value: '#169bbc',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#169bbc',
          type: 'color',
        },
        name: '600',
        attributes: {},
        path: ['spectrum', 'blue', '600'],
      },
      '700': {
        value: '#17829d',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#17829d',
          type: 'color',
        },
        name: '700',
        attributes: {},
        path: ['spectrum', 'blue', '700'],
      },
      '800': {
        value: '#18697e',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#18697e',
          type: 'color',
        },
        name: '800',
        attributes: {},
        path: ['spectrum', 'blue', '800'],
      },
      '900': {
        value: '#1a4f5e',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#1a4f5e',
          type: 'color',
        },
        name: '900',
        attributes: {},
        path: ['spectrum', 'blue', '900'],
      },
      '1000': {
        value: '#1b363f',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#1b363f',
          type: 'color',
        },
        name: '1000',
        attributes: {},
        path: ['spectrum', 'blue', '1000'],
      },
      '000': {
        value: '#ecf9fc',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#ecf9fc',
          type: 'color',
        },
        name: '000',
        attributes: {},
        path: ['spectrum', 'blue', '000'],
      },
    },
    green: {
      '100': {
        value: '#bbf1df',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#bbf1df',
          type: 'color',
        },
        name: '100',
        attributes: {},
        path: ['spectrum', 'green', '100'],
      },
      '200': {
        value: '#8ce7c9',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#8ce7c9',
          type: 'color',
        },
        name: '200',
        attributes: {},
        path: ['spectrum', 'green', '200'],
      },
      '300': {
        value: '#5eddb4',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#5eddb4',
          type: 'color',
        },
        name: '300',
        attributes: {},
        path: ['spectrum', 'green', '300'],
      },
      '400': {
        value: '#2fd39e',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#2fd39e',
          type: 'color',
        },
        name: '400',
        attributes: {},
        path: ['spectrum', 'green', '400'],
      },
      '500': {
        value: '#00c988',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#00c988',
          type: 'color',
        },
        name: '500',
        attributes: {},
        path: ['spectrum', 'green', '500'],
      },
      '600': {
        value: '#00ad76',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#00ad76',
          type: 'color',
        },
        name: '600',
        attributes: {},
        path: ['spectrum', 'green', '600'],
      },
      '700': {
        value: '#007552',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#007552',
          type: 'color',
        },
        name: '700',
        attributes: {},
        path: ['spectrum', 'green', '700'],
      },
      '800': {
        value: '#005940',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#005940',
          type: 'color',
        },
        name: '800',
        attributes: {},
        path: ['spectrum', 'green', '800'],
      },
      '900': {
        value: '#003d2e',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#003d2e',
          type: 'color',
        },
        name: '900',
        attributes: {},
        path: ['spectrum', 'green', '900'],
      },
      '1000': {
        value: '#00291f',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#00291f',
          type: 'color',
        },
        name: '1000',
        attributes: {},
        path: ['spectrum', 'green', '1000'],
      },
      '000': {
        value: '#f3fcf9',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#f3fcf9',
          type: 'color',
        },
        name: '000',
        attributes: {},
        path: ['spectrum', 'green', '000'],
      },
    },
    yellow: {
      '100': {
        value: '#ffeebe',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#ffeebe',
          type: 'color',
        },
        name: '100',
        attributes: {},
        path: ['spectrum', 'yellow', '100'],
      },
      '200': {
        value: '#ffe397',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#ffe397',
          type: 'color',
        },
        name: '200',
        attributes: {},
        path: ['spectrum', 'yellow', '200'],
      },
      '300': {
        value: '#ffd971',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#ffd971',
          type: 'color',
        },
        name: '300',
        attributes: {},
        path: ['spectrum', 'yellow', '300'],
      },
      '400': {
        value: '#ffce4a',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#ffce4a',
          type: 'color',
        },
        name: '400',
        attributes: {},
        path: ['spectrum', 'yellow', '400'],
      },
      '500': {
        value: '#ffc424',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#ffc424',
          type: 'color',
        },
        name: '500',
        attributes: {},
        path: ['spectrum', 'yellow', '500'],
      },
      '600': {
        value: '#ffad1f',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#ffad1f',
          type: 'color',
        },
        name: '600',
        attributes: {},
        path: ['spectrum', 'yellow', '600'],
      },
      '700': {
        value: '#fa8900',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#fa8900',
          type: 'color',
        },
        name: '700',
        attributes: {},
        path: ['spectrum', 'yellow', '700'],
      },
      '800': {
        value: '#e55c00',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#e55c00',
          type: 'color',
        },
        name: '800',
        attributes: {},
        path: ['spectrum', 'yellow', '800'],
      },
      '900': {
        value: '#c73f00',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#c73f00',
          type: 'color',
        },
        name: '900',
        attributes: {},
        path: ['spectrum', 'yellow', '900'],
      },
      '1000': {
        value: '#752100',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#752100',
          type: 'color',
        },
        name: '1000',
        attributes: {},
        path: ['spectrum', 'yellow', '1000'],
      },
      '000': {
        value: '#fff8e4',
        type: 'color',
        filePath: 'tokens/tokens_parsed.json',
        isSource: true,
        original: {
          value: '#fff8e4',
          type: 'color',
        },
        name: '000',
        attributes: {},
        path: ['spectrum', 'yellow', '000'],
      },
    },
  },
  fontFamilies: {
    'ivypresto-display': {
      value: 'IvyPresto Display',
      type: 'fontFamilies',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 'IvyPresto Display',
        type: 'fontFamilies',
      },
      name: 'ivypresto-display',
      attributes: {},
      path: ['fontFamilies', 'ivypresto-display'],
    },
    'sf-compact': {
      value: '\'SF Compact\', system-ui, sans-serif',
      type: 'fontFamilies',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 'SF Compact',
        type: 'fontFamilies',
      },
      name: 'sf-compact',
      attributes: {},
      path: ['fontFamilies', 'sf-compact'],
    },
    degular: {
      value: 'Degular',
      type: 'fontFamilies',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 'Degular',
        type: 'fontFamilies',
      },
      name: 'degular',
      attributes: {},
      path: ['fontFamilies', 'degular'],
    },
  },
  lineHeights: {
    '0': {
      value: 24,
      type: 'lineHeights',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 24,
        type: 'lineHeights',
      },
      name: '0',
      attributes: {},
      path: ['lineHeights', '0'],
    },
    '1': {
      value: 28,
      type: 'lineHeights',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 28,
        type: 'lineHeights',
      },
      name: '1',
      attributes: {},
      path: ['lineHeights', '1'],
    },
    '2': {
      value: 30,
      type: 'lineHeights',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 30,
        type: 'lineHeights',
      },
      name: '2',
      attributes: {},
      path: ['lineHeights', '2'],
    },
    '3': {
      value: 32,
      type: 'lineHeights',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 32,
        type: 'lineHeights',
      },
      name: '3',
      attributes: {},
      path: ['lineHeights', '3'],
    },
    '4': {
      value: 34,
      type: 'lineHeights',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 34,
        type: 'lineHeights',
      },
      name: '4',
      attributes: {},
      path: ['lineHeights', '4'],
    },
    '5': {
      value: 48,
      type: 'lineHeights',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 48,
        type: 'lineHeights',
      },
      name: '5',
      attributes: {},
      path: ['lineHeights', '5'],
    },
    '6': {
      value: 52,
      type: 'lineHeights',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 52,
        type: 'lineHeights',
      },
      name: '6',
      attributes: {},
      path: ['lineHeights', '6'],
    },
    '7': {
      value: 110,
      type: 'lineHeights',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 110,
        type: 'lineHeights',
      },
      name: '7',
      attributes: {},
      path: ['lineHeights', '7'],
    },
  },
  fontWeights: {
    'sf-compact-1': {
      value: 'medium',
      type: 'fontWeights',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 'medium',
        type: 'fontWeights',
      },
      name: 'sf-compact-1',
      attributes: {},
      path: ['fontWeights', 'sf-compact-1'],
    },
    'sf-compact-2': {
      value: 'semibold',
      type: 'fontWeights',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 'semibold',
        type: 'fontWeights',
      },
      name: 'sf-compact-2',
      attributes: {},
      path: ['fontWeights', 'sf-compact-2'],
    },
    'sf-compact-3': {
      value: 'bold',
      type: 'fontWeights',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 'bold',
        type: 'fontWeights',
      },
      name: 'sf-compact-3',
      attributes: {},
      path: ['fontWeights', 'sf-compact-3'],
    },
    'degular-0': {
      value: 'Thin',
      type: 'fontWeights',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 'Thin',
        type: 'fontWeights',
      },
      name: 'degular-0',
      attributes: {},
      path: ['fontWeights', 'degular-0'],
    },
    'degular-1': {
      value: 'Semibold',
      type: 'fontWeights',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 'Semibold',
        type: 'fontWeights',
      },
      name: 'degular-1',
      attributes: {},
      path: ['fontWeights', 'degular-1'],
    },
    'sf-compact-0': {
      value: 'regular',
      type: 'fontWeights',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 'regular',
        type: 'fontWeights',
      },
      name: 'sf-compact-0',
      attributes: {},
      path: ['fontWeights', 'sf-compact-0'],
    },
    'sf-compact-4': {
      value: 'regular italic',
      type: 'fontWeights',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 'regular italic',
        type: 'fontWeights',
      },
      name: 'sf-compact-4',
      attributes: {},
      path: ['fontWeights', 'sf-compact-4'],
    },
  },
  fontSize: {
    '0': {
      value: 13,
      type: 'fontSizes',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 13,
        type: 'fontSizes',
      },
      name: '0',
      attributes: {},
      path: ['fontSize', '0'],
    },
    '1': {
      value: 16,
      type: 'fontSizes',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 16,
        type: 'fontSizes',
      },
      name: '1',
      attributes: {},
      path: ['fontSize', '1'],
    },
    '2': {
      value: 18,
      type: 'fontSizes',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 18,
        type: 'fontSizes',
      },
      name: '2',
      attributes: {},
      path: ['fontSize', '2'],
    },
    '3': {
      value: 20,
      type: 'fontSizes',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 20,
        type: 'fontSizes',
      },
      name: '3',
      attributes: {},
      path: ['fontSize', '3'],
    },
    '4': {
      value: 22,
      type: 'fontSizes',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 22,
        type: 'fontSizes',
      },
      name: '4',
      attributes: {},
      path: ['fontSize', '4'],
    },
    '5': {
      value: 30,
      type: 'fontSizes',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 30,
        type: 'fontSizes',
      },
      name: '5',
      attributes: {},
      path: ['fontSize', '5'],
    },
    '6': {
      value: 44,
      type: 'fontSizes',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 44,
        type: 'fontSizes',
      },
      name: '6',
      attributes: {},
      path: ['fontSize', '6'],
    },
    '7': {
      value: 48,
      type: 'fontSizes',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 48,
        type: 'fontSizes',
      },
      name: '7',
      attributes: {},
      path: ['fontSize', '7'],
    },
    '8': {
      value: 140,
      type: 'fontSizes',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 140,
        type: 'fontSizes',
      },
      name: '8',
      attributes: {},
      path: ['fontSize', '8'],
    },
  },
  letterSpacing: {
    '0': {
      value: 0,
      type: 'letterSpacing',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 0,
        type: 'letterSpacing',
      },
      name: '0',
      attributes: {},
      path: ['letterSpacing', '0'],
    },
    '1': {
      value: '0%',
      type: 'letterSpacing',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: '0%',
        type: 'letterSpacing',
      },
      name: '1',
      attributes: {},
      path: ['letterSpacing', '1'],
    },
  },
  paragraphSpacing: {
    '0': {
      value: 0,
      type: 'paragraphSpacing',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 0,
        type: 'paragraphSpacing',
      },
      name: '0',
      attributes: {},
      path: ['paragraphSpacing', '0'],
    },
  },
  textCase: {
    none: {
      value: 'none',
      type: 'textCase',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 'none',
        type: 'textCase',
      },
      name: 'none',
      attributes: {},
      path: ['textCase', 'none'],
    },
  },
  textDecoration: {
    none: {
      value: 'none',
      type: 'textDecoration',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: 'none',
        type: 'textDecoration',
      },
      name: 'none',
      attributes: {},
      path: ['textDecoration', 'none'],
    },
  },
  consistent: {
    'consistent-white': {
      value: '#ffffff',
      type: 'color',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: '#ffffff',
        type: 'color',
      },
      name: 'consistent-white',
      attributes: {},
      path: ['consistent', 'consistent-white'],
    },
    'consistent-black': {
      value: '#000000',
      type: 'color',
      filePath: 'tokens/tokens_parsed.json',
      isSource: true,
      original: {
        value: '#000000',
        type: 'color',
      },
      name: 'consistent-black',
      attributes: {},
      path: ['consistent', 'consistent-black'],
    },
  },
  global: {
    spectrum: {
      gray: {
        '100': {
          value: '#f3f3f3',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#f3f3f3',
            type: 'color',
          },
          name: '100',
          attributes: {},
          path: ['global', 'spectrum', 'gray', '100'],
        },
        '200': {
          value: '#e6e6e6',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#e6e6e6',
            type: 'color',
          },
          name: '200',
          attributes: {},
          path: ['global', 'spectrum', 'gray', '200'],
        },
        '300': {
          value: '#b4b4b4',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#b4b4b4',
            type: 'color',
          },
          name: '300',
          attributes: {},
          path: ['global', 'spectrum', 'gray', '300'],
        },
        '400': {
          value: '#9b9b9b',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#9b9b9b',
            type: 'color',
          },
          name: '400',
          attributes: {},
          path: ['global', 'spectrum', 'gray', '400'],
        },
        '500': {
          value: '#818183',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#818183',
            type: 'color',
          },
          name: '500',
          attributes: {},
          path: ['global', 'spectrum', 'gray', '500'],
        },
        '600': {
          value: '#68686a',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#68686a',
            type: 'color',
          },
          name: '600',
          attributes: {},
          path: ['global', 'spectrum', 'gray', '600'],
        },
        '700': {
          value: '#4f4f51',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#4f4f51',
            type: 'color',
          },
          name: '700',
          attributes: {},
          path: ['global', 'spectrum', 'gray', '700'],
        },
        '800': {
          value: '#363638',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#363638',
            type: 'color',
          },
          name: '800',
          attributes: {},
          path: ['global', 'spectrum', 'gray', '800'],
        },
        '900': {
          value: '#1d1d1f',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#1d1d1f',
            type: 'color',
          },
          name: '900',
          attributes: {},
          path: ['global', 'spectrum', 'gray', '900'],
        },
        '1000': {
          value: '#000000',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#000000',
            type: 'color',
          },
          name: '1000',
          attributes: {},
          path: ['global', 'spectrum', 'gray', '1000'],
        },
        '000': {
          value: '#ffffff',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#ffffff',
            type: 'color',
          },
          name: '000',
          attributes: {},
          path: ['global', 'spectrum', 'gray', '000'],
        },
      },
      red: {
        '100': {
          value: '#ffe5e7',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#ffe5e7',
            type: 'color',
          },
          name: '100',
          attributes: {},
          path: ['global', 'spectrum', 'red', '100'],
        },
        '200': {
          value: '#ffc2c6',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#ffc2c6',
            type: 'color',
          },
          name: '200',
          attributes: {},
          path: ['global', 'spectrum', 'red', '200'],
        },
        '300': {
          value: '#ff9ea5',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#ff9ea5',
            type: 'color',
          },
          name: '300',
          attributes: {},
          path: ['global', 'spectrum', 'red', '300'],
        },
        '400': {
          value: '#f96c73',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#f96c73',
            type: 'color',
          },
          name: '400',
          attributes: {},
          path: ['global', 'spectrum', 'red', '400'],
        },
        '500': {
          value: '#f1465a',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#f1465a',
            type: 'color',
          },
          name: '500',
          attributes: {},
          path: ['global', 'spectrum', 'red', '500'],
        },
        '600': {
          value: '#e32144',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#e32144',
            type: 'color',
          },
          name: '600',
          attributes: {},
          path: ['global', 'spectrum', 'red', '600'],
        },
        '700': {
          value: '#be1332',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#be1332',
            type: 'color',
          },
          name: '700',
          attributes: {},
          path: ['global', 'spectrum', 'red', '700'],
        },
        '800': {
          value: '#990620',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#990620',
            type: 'color',
          },
          name: '800',
          attributes: {},
          path: ['global', 'spectrum', 'red', '800'],
        },
        '900': {
          value: '#650113',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#650113',
            type: 'color',
          },
          name: '900',
          attributes: {},
          path: ['global', 'spectrum', 'red', '900'],
        },
        '1000': {
          value: '#320109',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#320109',
            type: 'color',
          },
          name: '1000',
          attributes: {},
          path: ['global', 'spectrum', 'red', '1000'],
        },
        '000': {
          value: '#fff5f5',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#fff5f5',
            type: 'color',
          },
          name: '000',
          attributes: {},
          path: ['global', 'spectrum', 'red', '000'],
        },
      },
      blue: {
        '100': {
          value: '#c1ebf6',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#c1ebf6',
            type: 'color',
          },
          name: '100',
          attributes: {},
          path: ['global', 'spectrum', 'blue', '100'],
        },
        '200': {
          value: '#96ddef',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#96ddef',
            type: 'color',
          },
          name: '200',
          attributes: {},
          path: ['global', 'spectrum', 'blue', '200'],
        },
        '300': {
          value: '#6ad0e9',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#6ad0e9',
            type: 'color',
          },
          name: '300',
          attributes: {},
          path: ['global', 'spectrum', 'blue', '300'],
        },
        '400': {
          value: '#3fc2e2',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#3fc2e2',
            type: 'color',
          },
          name: '400',
          attributes: {},
          path: ['global', 'spectrum', 'blue', '400'],
        },
        '500': {
          value: '#14b4dc',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#14b4dc',
            type: 'color',
          },
          name: '500',
          attributes: {},
          path: ['global', 'spectrum', 'blue', '500'],
        },
        '600': {
          value: '#169bbc',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#169bbc',
            type: 'color',
          },
          name: '600',
          attributes: {},
          path: ['global', 'spectrum', 'blue', '600'],
        },
        '700': {
          value: '#17829d',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#17829d',
            type: 'color',
          },
          name: '700',
          attributes: {},
          path: ['global', 'spectrum', 'blue', '700'],
        },
        '800': {
          value: '#18697e',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#18697e',
            type: 'color',
          },
          name: '800',
          attributes: {},
          path: ['global', 'spectrum', 'blue', '800'],
        },
        '900': {
          value: '#1a4f5e',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#1a4f5e',
            type: 'color',
          },
          name: '900',
          attributes: {},
          path: ['global', 'spectrum', 'blue', '900'],
        },
        '1000': {
          value: '#1b363f',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#1b363f',
            type: 'color',
          },
          name: '1000',
          attributes: {},
          path: ['global', 'spectrum', 'blue', '1000'],
        },
        '000': {
          value: '#ecf9fc',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#ecf9fc',
            type: 'color',
          },
          name: '000',
          attributes: {},
          path: ['global', 'spectrum', 'blue', '000'],
        },
      },
      green: {
        '100': {
          value: '#bbf1df',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#bbf1df',
            type: 'color',
          },
          name: '100',
          attributes: {},
          path: ['global', 'spectrum', 'green', '100'],
        },
        '200': {
          value: '#8ce7c9',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#8ce7c9',
            type: 'color',
          },
          name: '200',
          attributes: {},
          path: ['global', 'spectrum', 'green', '200'],
        },
        '300': {
          value: '#5eddb4',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#5eddb4',
            type: 'color',
          },
          name: '300',
          attributes: {},
          path: ['global', 'spectrum', 'green', '300'],
        },
        '400': {
          value: '#2fd39e',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#2fd39e',
            type: 'color',
          },
          name: '400',
          attributes: {},
          path: ['global', 'spectrum', 'green', '400'],
        },
        '500': {
          value: '#00c988',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#00c988',
            type: 'color',
          },
          name: '500',
          attributes: {},
          path: ['global', 'spectrum', 'green', '500'],
        },
        '600': {
          value: '#00ad76',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#00ad76',
            type: 'color',
          },
          name: '600',
          attributes: {},
          path: ['global', 'spectrum', 'green', '600'],
        },
        '700': {
          value: '#007552',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#007552',
            type: 'color',
          },
          name: '700',
          attributes: {},
          path: ['global', 'spectrum', 'green', '700'],
        },
        '800': {
          value: '#005940',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#005940',
            type: 'color',
          },
          name: '800',
          attributes: {},
          path: ['global', 'spectrum', 'green', '800'],
        },
        '900': {
          value: '#003d2e',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#003d2e',
            type: 'color',
          },
          name: '900',
          attributes: {},
          path: ['global', 'spectrum', 'green', '900'],
        },
        '1000': {
          value: '#00291f',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#00291f',
            type: 'color',
          },
          name: '1000',
          attributes: {},
          path: ['global', 'spectrum', 'green', '1000'],
        },
        '000': {
          value: '#f3fcf9',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#f3fcf9',
            type: 'color',
          },
          name: '000',
          attributes: {},
          path: ['global', 'spectrum', 'green', '000'],
        },
      },
      yellow: {
        '100': {
          value: '#ffeebe',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#ffeebe',
            type: 'color',
          },
          name: '100',
          attributes: {},
          path: ['global', 'spectrum', 'yellow', '100'],
        },
        '200': {
          value: '#ffe397',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#ffe397',
            type: 'color',
          },
          name: '200',
          attributes: {},
          path: ['global', 'spectrum', 'yellow', '200'],
        },
        '300': {
          value: '#ffd971',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#ffd971',
            type: 'color',
          },
          name: '300',
          attributes: {},
          path: ['global', 'spectrum', 'yellow', '300'],
        },
        '400': {
          value: '#ffce4a',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#ffce4a',
            type: 'color',
          },
          name: '400',
          attributes: {},
          path: ['global', 'spectrum', 'yellow', '400'],
        },
        '500': {
          value: '#ffc424',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#ffc424',
            type: 'color',
          },
          name: '500',
          attributes: {},
          path: ['global', 'spectrum', 'yellow', '500'],
        },
        '600': {
          value: '#ffad1f',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#ffad1f',
            type: 'color',
          },
          name: '600',
          attributes: {},
          path: ['global', 'spectrum', 'yellow', '600'],
        },
        '700': {
          value: '#fa8900',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#fa8900',
            type: 'color',
          },
          name: '700',
          attributes: {},
          path: ['global', 'spectrum', 'yellow', '700'],
        },
        '800': {
          value: '#e55c00',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#e55c00',
            type: 'color',
          },
          name: '800',
          attributes: {},
          path: ['global', 'spectrum', 'yellow', '800'],
        },
        '900': {
          value: '#c73f00',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#c73f00',
            type: 'color',
          },
          name: '900',
          attributes: {},
          path: ['global', 'spectrum', 'yellow', '900'],
        },
        '1000': {
          value: '#752100',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#752100',
            type: 'color',
          },
          name: '1000',
          attributes: {},
          path: ['global', 'spectrum', 'yellow', '1000'],
        },
        '000': {
          value: '#fff8e4',
          type: 'color',
          filePath: 'tokens/tokens.json',
          isSource: true,
          original: {
            value: '#fff8e4',
            type: 'color',
          },
          name: '000',
          attributes: {},
          path: ['global', 'spectrum', 'yellow', '000'],
        },
      },
    },
    fontFamilies: {
      'ivypresto-display': {
        value: 'IvyPresto Display',
        type: 'fontFamilies',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: 'IvyPresto Display',
          type: 'fontFamilies',
        },
        name: 'ivypresto-display',
        attributes: {},
        path: ['global', 'fontFamilies', 'ivypresto-display'],
      },
      'sf-compact': {
        value: '\'SF Compact\', system-ui, sans-serif',
        type: 'fontFamilies',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: 'SF Compact',
          type: 'fontFamilies',
        },
        name: 'sf-compact',
        attributes: {},
        path: ['global', 'fontFamilies', 'sf-compact'],
      },
      degular: {
        value: 'Degular',
        type: 'fontFamilies',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: 'Degular',
          type: 'fontFamilies',
        },
        name: 'degular',
        attributes: {},
        path: ['global', 'fontFamilies', 'degular'],
      },
    },
    lineHeights: {
      '0': {
        value: '24',
        type: 'lineHeights',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '24',
          type: 'lineHeights',
        },
        name: '0',
        attributes: {},
        path: ['global', 'lineHeights', '0'],
      },
      '1': {
        value: '28',
        type: 'lineHeights',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '28',
          type: 'lineHeights',
        },
        name: '1',
        attributes: {},
        path: ['global', 'lineHeights', '1'],
      },
      '2': {
        value: '30',
        type: 'lineHeights',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '30',
          type: 'lineHeights',
        },
        name: '2',
        attributes: {},
        path: ['global', 'lineHeights', '2'],
      },
      '3': {
        value: '32',
        type: 'lineHeights',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '32',
          type: 'lineHeights',
        },
        name: '3',
        attributes: {},
        path: ['global', 'lineHeights', '3'],
      },
      '4': {
        value: '34',
        type: 'lineHeights',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '34',
          type: 'lineHeights',
        },
        name: '4',
        attributes: {},
        path: ['global', 'lineHeights', '4'],
      },
      '5': {
        value: '48',
        type: 'lineHeights',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '48',
          type: 'lineHeights',
        },
        name: '5',
        attributes: {},
        path: ['global', 'lineHeights', '5'],
      },
      '6': {
        value: '52',
        type: 'lineHeights',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '52',
          type: 'lineHeights',
        },
        name: '6',
        attributes: {},
        path: ['global', 'lineHeights', '6'],
      },
      '7': {
        value: '110',
        type: 'lineHeights',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '110',
          type: 'lineHeights',
        },
        name: '7',
        attributes: {},
        path: ['global', 'lineHeights', '7'],
      },
    },
    fontWeights: {
      'sf-compact-1': {
        value: 'medium',
        type: 'fontWeights',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: 'medium',
          type: 'fontWeights',
        },
        name: 'sf-compact-1',
        attributes: {},
        path: ['global', 'fontWeights', 'sf-compact-1'],
      },
      'sf-compact-2': {
        value: 'semibold',
        type: 'fontWeights',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: 'semibold',
          type: 'fontWeights',
        },
        name: 'sf-compact-2',
        attributes: {},
        path: ['global', 'fontWeights', 'sf-compact-2'],
      },
      'sf-compact-3': {
        value: 'bold',
        type: 'fontWeights',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: 'bold',
          type: 'fontWeights',
        },
        name: 'sf-compact-3',
        attributes: {},
        path: ['global', 'fontWeights', 'sf-compact-3'],
      },
      'degular-0': {
        value: 'Thin',
        type: 'fontWeights',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: 'Thin',
          type: 'fontWeights',
        },
        name: 'degular-0',
        attributes: {},
        path: ['global', 'fontWeights', 'degular-0'],
      },
      'degular-1': {
        value: 'Semibold',
        type: 'fontWeights',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: 'Semibold',
          type: 'fontWeights',
        },
        name: 'degular-1',
        attributes: {},
        path: ['global', 'fontWeights', 'degular-1'],
      },
      'sf-compact-0': {
        value: 'regular',
        type: 'fontWeights',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: 'regular',
          type: 'fontWeights',
        },
        name: 'sf-compact-0',
        attributes: {},
        path: ['global', 'fontWeights', 'sf-compact-0'],
      },
      'sf-compact-4': {
        value: 'regular italic',
        type: 'fontWeights',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: 'regular italic',
          type: 'fontWeights',
        },
        name: 'sf-compact-4',
        attributes: {},
        path: ['global', 'fontWeights', 'sf-compact-4'],
      },
    },
    fontSize: {
      '0': {
        value: '13',
        type: 'fontSizes',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '13',
          type: 'fontSizes',
        },
        name: '0',
        attributes: {},
        path: ['global', 'fontSize', '0'],
      },
      '1': {
        value: '16',
        type: 'fontSizes',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '16',
          type: 'fontSizes',
        },
        name: '1',
        attributes: {},
        path: ['global', 'fontSize', '1'],
      },
      '2': {
        value: '18',
        type: 'fontSizes',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '18',
          type: 'fontSizes',
        },
        name: '2',
        attributes: {},
        path: ['global', 'fontSize', '2'],
      },
      '3': {
        value: '20',
        type: 'fontSizes',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '20',
          type: 'fontSizes',
        },
        name: '3',
        attributes: {},
        path: ['global', 'fontSize', '3'],
      },
      '4': {
        value: '22',
        type: 'fontSizes',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '22',
          type: 'fontSizes',
        },
        name: '4',
        attributes: {},
        path: ['global', 'fontSize', '4'],
      },
      '5': {
        value: '30',
        type: 'fontSizes',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '30',
          type: 'fontSizes',
        },
        name: '5',
        attributes: {},
        path: ['global', 'fontSize', '5'],
      },
      '6': {
        value: '44',
        type: 'fontSizes',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '44',
          type: 'fontSizes',
        },
        name: '6',
        attributes: {},
        path: ['global', 'fontSize', '6'],
      },
      '7': {
        value: '48',
        type: 'fontSizes',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '48',
          type: 'fontSizes',
        },
        name: '7',
        attributes: {},
        path: ['global', 'fontSize', '7'],
      },
      '8': {
        value: '140',
        type: 'fontSizes',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '140',
          type: 'fontSizes',
        },
        name: '8',
        attributes: {},
        path: ['global', 'fontSize', '8'],
      },
    },
    letterSpacing: {
      '0': {
        value: '0',
        type: 'letterSpacing',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '0',
          type: 'letterSpacing',
        },
        name: '0',
        attributes: {},
        path: ['global', 'letterSpacing', '0'],
      },
      '1': {
        value: '0%',
        type: 'letterSpacing',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '0%',
          type: 'letterSpacing',
        },
        name: '1',
        attributes: {},
        path: ['global', 'letterSpacing', '1'],
      },
    },
    paragraphSpacing: {
      '0': {
        value: '0',
        type: 'paragraphSpacing',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '0',
          type: 'paragraphSpacing',
        },
        name: '0',
        attributes: {},
        path: ['global', 'paragraphSpacing', '0'],
      },
    },
    textCase: {
      none: {
        value: 'none',
        type: 'textCase',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: 'none',
          type: 'textCase',
        },
        name: 'none',
        attributes: {},
        path: ['global', 'textCase', 'none'],
      },
    },
    textDecoration: {
      none: {
        value: 'none',
        type: 'textDecoration',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: 'none',
          type: 'textDecoration',
        },
        name: 'none',
        attributes: {},
        path: ['global', 'textDecoration', 'none'],
      },
    },
    consistent: {
      'consistent-white': {
        value: '#ffffff',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.000}',
          type: 'color',
        },
        name: 'consistent-white',
        attributes: {},
        path: ['global', 'consistent', 'consistent-white'],
      },
      'consistent-black': {
        value: '#000000',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.1000}',
          type: 'color',
        },
        name: 'consistent-black',
        attributes: {},
        path: ['global', 'consistent', 'consistent-black'],
      },
    },
    featuredContext: {
      'featuredContext-primary': {
        value: '#000000',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{consistent.consistent-black}',
          type: 'color',
        },
        name: 'featuredContext-primary',
        attributes: {},
        path: ['global', 'featuredContext', 'featuredContext-primary'],
      },
      'featuredContext-secondary': {
        value: '#ffffff',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{consistent.consistent-white}',
          type: 'color',
        },
        name: 'featuredContext-secondary',
        attributes: {},
        path: ['global', 'featuredContext', 'featuredContext-secondary'],
      },
    },
  },
  dark: {
    icon: {
      'icon-primary': {
        value: '#ffffff',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.000}',
          type: 'color',
        },
        name: 'icon-primary',
        attributes: {},
        path: ['dark', 'icon', 'icon-primary'],
      },
      'icon-secondary': {
        value: '#000000',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.1000}',
          type: 'color',
        },
        name: 'icon-secondary',
        attributes: {},
        path: ['dark', 'icon', 'icon-secondary'],
      },
    },
    button: {
      'button-primary': {
        value: '#ffffff',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.000}',
          type: 'color',
        },
        name: 'button-primary',
        attributes: {},
        path: ['dark', 'button', 'button-primary'],
      },
      'button-secondary': {
        value: '#000000',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.1000}',
          type: 'color',
        },
        name: 'button-secondary',
        attributes: {},
        path: ['dark', 'button', 'button-secondary'],
      },
      'button-disabled': {
        value: '#9b9b9b',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.400}',
          type: 'color',
        },
        name: 'button-disabled',
        attributes: {},
        path: ['dark', 'button', 'button-disabled'],
      },
    },
    surface: {
      'surface-primary': {
        value: '#1d1d1f',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.900}',
          type: 'color',
        },
        name: 'surface-primary',
        attributes: {},
        path: ['dark', 'surface', 'surface-primary'],
      },
      'surface-secondary': {
        value: '#e6e6e6',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.200}',
          type: 'color',
        },
        name: 'surface-secondary',
        attributes: {},
        path: ['dark', 'surface', 'surface-secondary'],
      },
    },
    text: {
      'text-primary': {
        value: '#ffffff',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.000}',
          type: 'color',
        },
        name: 'text-primary',
        attributes: {},
        path: ['dark', 'text', 'text-primary'],
      },
      'text-secondary': {
        value: '#000000',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.1000}',
          type: 'color',
        },
        name: 'text-secondary',
        attributes: {},
        path: ['dark', 'text', 'text-secondary'],
      },
      'text-tertiary': {
        value: '#68686a',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.600}',
          type: 'color',
        },
        name: 'text-tertiary',
        attributes: {},
        path: ['dark', 'text', 'text-tertiary'],
      },
    },
    border: {
      'border-primary': {
        value: '#b4b4b4',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.300}',
          type: 'color',
        },
        name: 'border-primary',
        attributes: {},
        path: ['dark', 'border', 'border-primary'],
      },
    },
  },
  light: {
    icon: {
      'icon-primary': {
        value: '#000000',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.1000}',
          type: 'color',
        },
        name: 'icon-primary',
        attributes: {},
        path: ['light', 'icon', 'icon-primary'],
      },
      'icon-secondary': {
        value: '#ffffff',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.000}',
          type: 'color',
        },
        name: 'icon-secondary',
        attributes: {},
        path: ['light', 'icon', 'icon-secondary'],
      },
    },
    button: {
      'button-primary': {
        value: '#000000',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.1000}',
          type: 'color',
        },
        name: 'button-primary',
        attributes: {},
        path: ['light', 'button', 'button-primary'],
      },
      'button-secondary': {
        value: '#ffffff',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.000}',
          type: 'color',
        },
        name: 'button-secondary',
        attributes: {},
        path: ['light', 'button', 'button-secondary'],
      },
      'button-disabled': {
        value: '#9b9b9b',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.400}',
          type: 'color',
        },
        name: 'button-disabled',
        attributes: {},
        path: ['light', 'button', 'button-disabled'],
      },
    },
    surface: {
      'surface-primary': {
        value: '#e6e6e6',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.200}',
          type: 'color',
        },
        name: 'surface-primary',
        attributes: {},
        path: ['light', 'surface', 'surface-primary'],
      },
      'surface-secondary': {
        value: '#1d1d1f',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.900}',
          type: 'color',
        },
        name: 'surface-secondary',
        attributes: {},
        path: ['light', 'surface', 'surface-secondary'],
      },
    },
    text: {
      'text-primary': {
        value: '#000000',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.1000}',
          type: 'color',
        },
        name: 'text-primary',
        attributes: {},
        path: ['light', 'text', 'text-primary'],
      },
      'text-secondary': {
        value: '#ffffff',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.000}',
          type: 'color',
        },
        name: 'text-secondary',
        attributes: {},
        path: ['light', 'text', 'text-secondary'],
      },
      'text-tertiary': {
        value: '#68686a',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.600}',
          type: 'color',
        },
        name: 'text-tertiary',
        attributes: {},
        path: ['light', 'text', 'text-tertiary'],
      },
    },
    border: {
      'border-primary': {
        value: '#1d1d1f',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '{spectrum.gray.900}',
          type: 'color',
        },
        name: 'border-primary',
        attributes: {},
        path: ['light', 'border', 'border-primary'],
      },
    },
  },
  'user\'s featured color': {
    featuredContext: {
      'featuredContext-primary': {
        value: '#3f9ff5',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '#3f9ff5',
          type: 'color',
        },
        name: 'featuredContext-primary',
        attributes: {},
        path: [
          'user\'s featured color',
          'featuredContext',
          'featuredContext-primary',
        ],
      },
      'featuredContext-secondary': {
        value: '#CdaF75',
        type: 'color',
        filePath: 'tokens/tokens.json',
        isSource: true,
        original: {
          value: '#CdaF75',
          type: 'color',
        },
        name: 'featuredContext-secondary',
        attributes: {},
        path: [
          'user\'s featured color',
          'featuredContext',
          'featuredContext-secondary',
        ],
      },
    },
  },
}
